### ISSUE TITLE
Permission issue to open pull request for a new test scenarios

### ISSUE THREAD

**Issue by ardaekinci** [uyaritu/fp2020-tests#1]
I cannot push my branch to open a pull request due to permission error.
Here are my local commits and new test cases.
* add a test case to cover sum equals to goal condition for every color 
* add a test case to cover 0 scores by drawing same colors (preliminary score is 1)  
* add test cases to check error raise for createCard function  
* add boundary tests for part1  

I added boundary tests for part 1 that are testing the same year and the condition of start year > end year.
For the second part, I added 6 new test cases, 2 of them are testing the error of suit and rank conversion of the card.
The other 4 are testing the getting 0 scores by different kinds of plays. (E.g. drawing the same color with 1 preliminary score).

* While testing `suit is unknown` error by drawing only one card, I found a bug in my code. According to implementation, that test might catch a bug.

I added my tests here temporarily https://github.com/ardaekinci/BLG458-Tests.

When `permission denied` problem solves, I will push my code to open a pull request.

**Comment by uyar** [comment]
Can you verify that you have followed this procedure?

- fork the repository
- commit and push to your fork
- generate pull request

**Comment by uyar** [comment]
I'm guessing that your repo is an independent repo and not a fork.

**Comment by ardaekinci** [comment]
Thanks for the update.
